import 'dart:typed_data';

class ToDoTask {
  final int usId;
  final int taskId;
  final String taskName;
  String? taskDesc;
  final DateTime startDate;
  final DateTime dueDate;
  String? priority;
  final String remind;
  final String status;
  final String category;
  String? labels;
  final String createDate;

  ToDoTask(
      {
    required this.usId,
    required this.taskId,
    required this.taskName,
    this.taskDesc,
    required this.startDate,
    required this.dueDate,
    this.priority,
    required this.remind,
    required this.status,
    required this.category,
    this.labels,
    required this.createDate,
  });

  factory ToDoTask.fromJson(Map<String, dynamic> json){
    return ToDoTask(
        usId: json['usid'],
        taskId: json['taskId'],
        taskName: json['taskName'],
        startDate: json['startDate'],
        dueDate: json['dueDate'],
        remind: json['remind'],
        status: json['status'],
        category: json['category'],
        createDate: json['createDate']
    );
  }
}

class Users {
  final int userId; // Nullable as it's generated by the database
  final String name;
  final String email;
  final String phoneNumber;
  final String password;
  final String userType;
  Uint8List? profilePicture;

  Users({
    required this.userId,
    required this.name,
    required this.email,
    required this.phoneNumber,
    required this.password,
    required this.userType,
    this.profilePicture,
  });

  factory Users.fromJson(Map<String, dynamic> json) {
    return Users(
      userId: json['userId'],
      name: json['name'],
      email: json['email'],
      phoneNumber: json['phoneNumber'],
      password: json['password'],
      userType: json['userType'],
      profilePicture: json['profilePicture'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'userId': userId,
      'name': name,
      'email': email,
      'phoneNumber': phoneNumber,
      'password': password,
      'userType': userType,
      'profilePicture': profilePicture,
    };
  }
}
