name: pup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  anim_search_bar: ^2.0.3
  flutter_local_notifications: ^15.1.1
  device_info_plus:
  image:
  timezone:
  flutter_timezone:
  google_fonts: 4.0.3
  badges:
  intl:
  provider: 6.0.4
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  flutter_side_menu:
  flutter_screenutil:
  flutter_staggered_grid_view:
  firebase_auth:
  flutter_otp_text_field:
  toggle_switch:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  percent_indicator:
  alphabet_scroll_view: ^0.3.2
  pin_code_fields:
  carousel_slider:
  http:
  image_picker:
 # contacts_service: ^0.6.3
  fast_contacts: ^3.0.3
  permission_handler: ^11.0.0
  scroll_to_hide: ^2.0.1
  sticky_headers: ^0.3.0+2
  flutter_clean_calendar:
  table_calendar: ^3.0.1
  line_icons: ^2.0.1
  path_provider: ^2.0.15
  flutter_slidable: ^3.0.0
  shared_preferences:
  awesome_snackbar_content:
  firebase_core: ^2.16.0
  url_launcher:
  quill_html_editor:
  flutter_colorpicker:
  omni_datetime_picker: ^1.0.9
  syncfusion_flutter_signaturepad:
  syncfusion_flutter_pdf:
  pdf:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Qeilab
       fonts:
         - asset: lib/assets/font/Qeilab.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Voyager
       fonts:
         - asset: lib/assets/font/VoyagerMedium.otf
     - family: Linle
       fonts:
         - asset: lib/assets/font/LinlegreyRegular.ttf
     - family: pupicon
       fonts:
         - asset: lib/assets/font/pupicon.ttf
     - family: lineicon
       fonts:
         - asset: lib/assets/font/lineicon.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
