import 'package:flutter/material.dart';
var pink=Color(0xFFEDE0EA);
var green=Color(0xFFE0EBDD);
var purple=Color(0xFFEBE3FB);
var brown=Color(0xFFEDEBDE);
var blue=Color(0xFFDEECEC);
var orange=Color(0xFFECE0DE);
var red=Color(0xFFECDEDE);
var yellow=Color(0xE5ECE9DE);